### ISSUE TITLE
Invalid `--%` Option for `knife` command in DevOps200.2x Lab4- Deploy App with Chef on Azure

### ISSUE THREAD

**Issue by dingliu** [Microsoft/PartsUnlimitedMRP#145]
### Functional Impact

The `knife`  command provided in step 3 fails to bootstrap the VM.

### Minimal repro steps

Follow the lab steps in the [instruction page](https://github.com/Microsoft/PartsUnlimitedMRP/blob/gh-pages/_posts/2018-01-08-200.2x-IaC-DeployappwithChefonAzure.md), to task 5 step 3.

### Expected result

The `knife` command bootstraps the VM successfully.

### Actual result

The `knife` command quits with following error message (please click the image to enlarge it):

![2018-07-08_1-14-41_ms_devops2002x_lab4_chef1_task5_step3_knife_invalid_option](https://user-images.githubusercontent.com/888873/42429549-7b761516-8307-11e8-9baf-d88604f50175.png)

### Further technical details

The second screepshot in step 3 actually removed the invalid option `--%`.

**Comment by eamonnk** [comment]
This has been fixed with the PR #146 merged as listed above. Thanks again for taking the time to investigate and submit a PR dingliu.

Thanks,
Eamonn

**Comment by dingliu** [comment]
You are always welcome. I'm closing this issue.
