### ISSUE TITLE
Continuous Deployment with VSTS and VSTS Hosted Agent Issue

### ISSUE THREAD

**Issue by pavankumar9491** [Microsoft/PartsUnlimitedMRP#159]
Hi ,

I am facing issues when the power shell script runs. I am not able to connect to the host through ssh
![image](https://user-images.githubusercontent.com/28778628/55425777-e369c980-55a0-11e9-90fe-eb451b9129b5.png)

Can somebody help me pls.

Thanks in advance :)

**Comment by pavankumar9491** [comment]
@julienstroheker 
Could you please help me out in this issue?

**Comment by eamonnk** [comment]
Hi, 

I'll have a look at this, see can I repro it. it will be later today when I get back to you.

Thanks,
Eamonn

**Comment by pavankumar9491** [comment]
Hi @eamonnk ,

Any update about this issue ?

**Comment by eamonnk** [comment]
HI, 

Been a bit delayed getting to it, but will have an update later today, 

Will talk then, Thanks,
Eamonn

**Comment by eamonnk** [comment]
Hi, 

Sorry for the delay getting back, finally got through this this morning and it ran fine, so functionally its working as expected. 

The error suggests its something to do with the connection to the deployed VM, and either the dns name or one of the variable definitions in the pipeline.

Can you lok at the end of the steps in the labs [Continuous Deployment with VSTS and VSTS Hosted Agent ](http://microsoft.github.io/PartsUnlimitedMRP/cicd/200.3x-CICD-CDwithHostedAgent.html) and verify the variables, try connect ot the VM via PuTTy/ssh and ensure the username, password and dnsname are correct as defined in your pipeline i.e. sshtarget, sshuser and sshPassword and that there are no whitespaces in the release task definition where these items are called?

Thanks,
Eamonn

**Comment by eamonnk** [comment]
closing issue as no response and confirmed lab is working as expected.
