### ISSUE TITLE
CD HOL - azure-cli install issue

### ISSUE THREAD

**Issue by dtzar** [Microsoft/PartsUnlimitedMRP#33]
If you follow the instructions to install the CLI the way mentioned "npm install azure-cli" then when you just type "azure" it is not a recognized command.  I recommend changing this install to "sudo npm install azure-cli -g"  -g is the global switch so azure can be recognized from anywhere.

**Comment by julienstroheker** [comment]
Same thing here David :)
Maybe we can add this in the MD file ?

**Comment by dtzar** [comment]
@OguzPastirmaci said he is working to resolve this

**Comment by OguzPastirmaci** [comment]
@julienstroheker is working on a fix.
