### ISSUE TITLE
Newer version of VSTS

### ISSUE THREAD

**Issue by jgardner04** [Microsoft/PartsUnlimitedMRP#68]
Based on the images, I am on a different version of VSTS.  When running the Publish artifact, I need to use the  Copy and Publish option.  I end up with a successful completion but it is clear that the script deploy does not work because it can't find the files .jar files.  I end up with an error that the files don't exist.

**Comment by julienstroheker** [comment]
Hi @jgardner04 

I guess you are doing the HOL about Continuous Integration ?

We know about this old setup and we are updating the content, we should merge the updates next week.

Thanks

**Comment by jgardner04** [comment]
@julienstroheker awesome.  I am happy to help contribute if you would like.

**Comment by julienstroheker** [comment]
@jgardner04 the HOL on Continuous Integration is now updated and should work ;)
Let me know if it's also ok on your side if you have the time to test it.
Thanks for your feedbacks and the others HOL should be updated in the next days.
J.
