### ISSUE TITLE
Step 3 in the Continuous Deployment

### ISSUE THREAD

**Issue by gitwilbug1** [Microsoft/PartsUnlimitedMRP#72]
3. SSH into the Azure Virtual Machine that you turned into a Visual Studio Team Services Build Agent

I dont see instructions for the VSTS Build Agent.

**Comment by julienstroheker** [comment]
Hey @gitwilbug1 

We are currently reviewing this Hand on Labs, it should be modified this week.

Thanks for the feedback.

**Comment by julienstroheker** [comment]
@gitwilbug1 should be fixed now using the new Hands on Labs

**Comment by gitwilbug1** [comment]
Thanks again for replying.  I was able to search around and figure out how to build a vsts agent on Ubuntu. I had a lot of trouble with the /deploy/Upload-Deploy-Artifacts.sh.  The azure-cli commands seem to be outdated.,
