### ISSUE TITLE
MRP Deployment using xPlat CLI Issue

### ISSUE THREAD

**Issue by Benji-Yarmand** [Microsoft/PartsUnlimitedMRP#79]
Hi guys

I'm trying to go through this [HOL](https://github.com/Microsoft/PartsUnlimitedMRP/blob/master/docs/HOL-Integration-Services.md) which has a link to [this one](https://github.com/Microsoft/PartsUnlimitedMRP/blob/master/docs/HOL-Deploying-MRP-with-xPlat-CLI-Infrastructure-as-Code.md)

It uses some file which do not exist anymore! 
ProvisoinLinuxVM-xplat-cli.sh
ProvisionAzureLinuxVM.sh
Install-MRP.sh

All I need right now is a simple/fast way to deploy MRP (just once) so I can move on to integration part.
I see there are different deployment strategies, it seems the files and docs are out of sync.

I appreciate your help.

**Comment by julienstroheker** [comment]
Hey @Benji-Yarmand 
Thanks for raising this issue, the short answer that I can give you if you want to quickly deploy the MRP app on an Ubuntu VM is to : 
* Run the Install-Build-Dependencies.sh on it
* Download the two packages : ordering-service-0.1.0.jar and mrp.war from the builds folder of this repo in the following folder on the VM : /var/lib/partsunlimited (Create the folder)
* Finally run the following script : deploy_mrp_app.sh

About the integration part of PU and MRP I am not sure if it's gonna works, like you said this HOL content need to be updated.

Hope it helps.

**Comment by Benji-Yarmand** [comment]
Hi @julienstroheker 
Thank you for prompt response, and for your help.

I've tried Install-Build-Dependencies.sh on my Ubuntu vm, but failed with the following message.
I have Ubuntu 14.04. I'm going to try it on 16.04

`Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
`

Thank you.

**Comment by julienstroheker** [comment]
I recommend you to use a 16.04 indeed.

Give me news on how it is going :)

Thanks

**Comment by Benji-Yarmand** [comment]
Thank you @julienstroheker 

Those scripts were great! I successfully installed MRP on my Ubuntu vm on Azure using them.

In Install-Build-Dependencies.sh :
comment
`sudo apt-get install npm -y` because we are using a PPA to install nodejs, and it already contains npm
add
`sudo apt-get install tomcat7`

And in deploy_mrp_app.sh:
comment
`# Create deployment directory
sudo mkdir -p /var/lib/partsunlimited

# Remove old artifacts
sudo rm -f /var/lib/partsunlimited/MongoRecords.js*
sudo rm -f /var/lib/partsunlimited/mrp.war*
sudo rm -f /var/lib/partsunlimited/ordering-service-0.1.0.jar*

# Copy files from deployment package
sudo find ../ -iname '*.?ar' -exec cp -t /var/lib/partsunlimited {} +;
sudo find . -iname 'MongoRecords.js' -exec cp -t /var/lib/partsunlimited {} +;
`

I also copied MongoRecords.js.

I now move on to integration part :)

Thank you again.

**Comment by julienstroheker** [comment]
Awesome! 

Thanks for the feedback. 

Good luck on the Integration part,  I am not very comfortable on that one but I am curious to know if it still works. 

Let me know.
