### ISSUE TITLE
HOL-Integration-Services - SQL Azure DB

### ISSUE THREAD

**Issue by Benji-Yarmand** [Microsoft/PartsUnlimitedMRP#87]
Hi @julienstroheker 

After you helped me to solve MRP deployment issue, I moved to HOL-Integration-Services.

As you said it was not quite straight :)

After fixing couple of small issues, now I found out that my Azure SQL DBs have a schema (PartsUnlimitedDB) with NO TABLE inside! Having a look at the code it seems we are using a in-memory storage/database.

Notice that the integration doc is based on reading/writing to the database.

Questions: 
1) Is the e-commerce solution still using Azure SQL DB? 
2) Can the old "HOL-Integration-Services" be fixed with some small updates?
3) If not, what do we do for integrating MRP and e-commerce? 

I appreciate your time mate.
Thanks.

**Comment by julienstroheker** [comment]
To be honest I never tried the integration part..

Maybe @OguzPastirmaci can help you on this.

Thanks

**Comment by OguzPastirmaci** [comment]
Hi @Benji-Yarmand, we are in the process of updating the Parts Unlimited content, so let me have a look and try to see if that issue would be fixed with the content refresh.

**Comment by julienstroheker** [comment]
Closing that one for now with two tags. 
Still discussing internally if we need this scenario.

Thanks
