### ISSUE TITLE
HOL-ContinuousDeployment requires DotNetFramework

### ISSUE THREAD

**Issue by eloekset** [Microsoft/PartsUnlimitedMRP#92]
The build runs successfully, but deployment does not.

The reason seems to be a Demand on DotNetFramework that cannot be removed. I assume it's because we use PowerShell to run a deployment script.

![2016-10-10_20-19-17](https://cloud.githubusercontent.com/assets/791721/19246498/ee6e3124-8f26-11e6-8791-f7122d614921.png)

**Comment by julienstroheker** [comment]
Hi @eloekset ,

Thanks to your issue, I just realized a mistake in the HOL screenshot. You have to pick the **Hosted** Deployment Queue to run the PS Script, not the MRP one.

Thanks

**Comment by eloekset** [comment]
Thanks! I was confused by the screenshot you've just fixed in a PR.

**Comment by julienstroheker** [comment]
No worries.
Thanks for raising this issue :)
